# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  gradle:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

commands:
  gradle-build:
    description: "Execute a gradle-wrapper build with a specific version and conditionally upload it"
    parameters:
      version:
        type: string
      upload:
        type: boolean
        default: false
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      #
      - run: |
          export ORG_GRADLE_PROJECT_VERSION="<< parameters.version >>"
          echo "ORG_GRADLE_PROJECT_VERSION=${ORG_GRADLE_PROJECT_VERSION}"
          ./gradlew build <<# parameters.upload >> bintrayUpload <</ parameters.upload >>
      #
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - store_artifacts:
          path: build/libs

jobs:
  build:
    executor: gradle
    steps:
      - checkout
      - gradle-build:
          version: ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          upload: false
  release-build:
    executor: gradle
    steps:
      - checkout
      - gradle-build:
          version: ${CIRCLE_TAG}
          upload: true

workflows:
  build:
    jobs:
      - build:
          context: kuberig-context
  release:
    jobs:
      - release-build:
          context: kuberig-context
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/