# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: kuberig-context
          jobs:
            - build:
                - pre-steps:
                    - run:
                        - command: export ORG_GRADLE_PROJECT_VERSION="${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
      - release:
          context: kuberig-context
          filters:
            tags:
              only:
                - /.*/
          jobs:
            - build-and-upload:
                - pre-steps:
                    - run:
                        - command: export ORG_GRADLE_PROJECT_VERSION="${CIRCLE_TAG}"

executors:
  gradle:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

commands:
  gradle-build:
    description: "Execute a gradle-wrapper build with a specific version and conditionally upload it"
    parameters:
      upload:
        type: boolean
        default: false
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      #
      - run: ./gradlew build <<# parameters.upload >> bintrayUpload <</ parameters.upload >>
      #
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - store_artifacts:
          path: build/libs

jobs:
  build:
    executor: gradle
    steps:
      - checkout
      - gradle-build:
          upload: false
  release-build:
    executor: gradle
    steps:
      - checkout
      - gradle-build
          upload: true