/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.kuberig.dsl.vanilla.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'io.kuberig.dsl.vanilla.plugin.greeting' plugin.
 */
class KuberigDslVanillaPluginPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.kuberig.dsl.vanilla.plugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
